# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'venabout.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(350, 160)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(350, 160))
        Dialog.setMaximumSize(QtCore.QSize(350, 160))
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 331, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblAboutNombre = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblAboutNombre.setObjectName("lblAboutNombre")
        self.gridLayout.addWidget(self.lblAboutNombre, 2, 1, 1, 1)
        self.AboutVersion = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AboutVersion.setObjectName("AboutVersion")
        self.gridLayout.addWidget(self.AboutVersion, 1, 2, 1, 1)
        self.AboutNombre = QtWidgets.QLabel(self.gridLayoutWidget)
        self.AboutNombre.setObjectName("AboutNombre")
        self.gridLayout.addWidget(self.AboutNombre, 2, 2, 1, 1)
        self.lblLogo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/logo/logo.png"))
        self.lblLogo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.gridLayout.addWidget(self.lblLogo, 0, 0, 1, 4)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.lblAboutVersion = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblAboutVersion.setObjectName("lblAboutVersion")
        self.gridLayout.addWidget(self.lblAboutVersion, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.btnAboutCerrar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnAboutCerrar.setObjectName("btnAboutCerrar")
        self.gridLayout.addWidget(self.btnAboutCerrar, 3, 1, 1, 2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblAboutNombre.setText(_translate("Dialog", "Nombre:"))
        self.AboutVersion.setText(_translate("Dialog", "0.0.1"))
        self.AboutNombre.setText(_translate("Dialog", "Miguel"))
        self.lblAboutVersion.setText(_translate("Dialog", "Version:"))
        self.btnAboutCerrar.setText(_translate("Dialog", "Cerrar"))
import logo_rc
