# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vencalendar.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_venCalendar(object):
    def setupUi(self, venCalendar):
        venCalendar.setObjectName("venCalendar")
        venCalendar.setWindowModality(QtCore.Qt.ApplicationModal)
        venCalendar.resize(330, 201)
        venCalendar.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(venCalendar)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.calendar = QtWidgets.QCalendarWidget(venCalendar)
        self.calendar.setObjectName("calendar")
        self.gridLayout_2.addWidget(self.calendar, 0, 0, 1, 1)

        self.retranslateUi(venCalendar)
        QtCore.QMetaObject.connectSlotsByName(venCalendar)

    def retranslateUi(self, venCalendar):
        _translate = QtCore.QCoreApplication.translate
        venCalendar.setWindowTitle(_translate("venCalendar", "Fecha Alta"))
